//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcCrudOperation.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Employee
    {
        public int emp_id { get; set; }

        [Display(Name ="Employee Name :")]
        [Required(ErrorMessage ="Employee name is Require!")]
        [MinLength(3,ErrorMessage ="Minimum 3 character is allowed")]
        [MaxLength(15,ErrorMessage ="Maximum 15 character is allowed")]
        public string emp_name { get; set; }

        [Display(Name = "Employee Salary :")]
        [Required(ErrorMessage = "Employee salary is Require!")]
        public Nullable<decimal> emp_salary { get; set; }

        [Display(Name = "Employee Designation :")]
        [Required(ErrorMessage = "Employee designation is Require!")]
        public string emp_designation { get; set; }
    }
}
